version: '3.7'

services:
  verdaccio:
    image: verdaccio/verdaccio
    networks:
      - prod_default
    volumes:
      - ~/verdaccio/storage:/verdaccio/storage
    ports:
      - "4873:4873"
networks:
  prod_default:
    external: true